config/routes.rb
Spina::Engine.routes.draw do
  namespace :admin do
    resources :projects do
      post :sort, on: :collection
    end
  end
end

app/models/spina/project.rb
module Spina
  class Project < ActiveRecord::Base
    extend FriendlyId
    friendly_id :title, use: [:slugged, :finders]

    belongs_to :project_category, optional: true
    belongs_to :image_collection, optional: true, class_name: "Spina::ImageCollection"
    belongs_to :image, class_name: "Spina::Image"

    accepts_nested_attributes_for :image_collection

    validates :title, :description, :image, :publish_date, presence: true
    validates :slug, uniqueness: true

    scope :by_newest, -> { order(publish_date: :DESC) }
    scope :by_position, -> { order(position: :ASC) }
    scope :is_live, -> { where("publish_date <= ? AND draft = ?", Date.today, 0) }

    def live?
      self.publish_date <= Date.today && draft.zero?
    end

    def scheduled?
      self.publish_date >= Date.today && draft.zero?
    end

    def draft?
      draft == 1
    end
  end
end

app/models/spina/project_category.rb
module Spina
  class ProjectCategory < ActiveRecord::Base
    has_many :projects

    validates :name, presence: true
  end
end

app/controllers/spina/admin/projects_controller.rb
module Spina
  module Admin
    class ProjectsController < AdminController
      before_action :set_breadcrumb
      before_action :set_project, only: [:show, :edit, :update, :destroy]

      layout "spina/admin/admin"

      def show
      end

      def index
        @projects = Project.by_position
      end

      def new
        add_breadcrumb "New project", spina.new_admin_project_path
        @project = Project.new
      end

      def edit
        add_breadcrumb @project.title
      end

      def create
        add_breadcrumb "New project"
        @project = Project.new(project_params)
        if @project.save
          redirect_to spina.admin_projects_url
        else
          render :new
        end
      end

      def update
        add_breadcrumb @project.title
        if @project.update_attributes(project_params)
          redirect_to spina.admin_projects_url
        else
          render :edit
        end
      end

      def destroy
        @project.destroy
        redirect_to spina.admin_projects_url
      end

      def sort
        params[:list].each_pair do |parent_pos, parent_node|
          update_project_position(parent_node, parent_pos)
        end
        head :ok
      end

      private

      def set_project
        @project = Project.find(params[:id])
      end

      def set_breadcrumb
        add_breadcrumb "Projects", spina.admin_projects_path
      end

      def update_project_position(project, position)
        Spina::Project.update(project[:id], position: position.to_i + 1)
      end

      def project_params
        params.require(:project).permit(
          :completion_date,
          :description,
          :draft,
          :duration,
          :image_collection_id,
          :image_id,
          :location,
          :project_category_id,
          :publish_date,
          :seo_description,
          :seo_title,
          :slug,
          :testimonial_name,
          :testimonial,
          :title,
          image_collection_attributes: [:image_tokens, :image_positions],
        )
      end
    end
  end
end

app/views/spina/admin/hooks/projects/_website_secondary_navigation.html.haml
%li{ class: ('active' if current_page?(admin_projects_path)) }
  = link_to 'Projects', spina.admin_projects_path
%li{ class: ('active' if current_page?(admin_projects_categories_path)) }
  = link_to 'Projects Categories', spina.admin_projects_categories_path

app/views/spina/admin/projects/_form.html.haml
- if @project.errors.any?
  - content_for :notifications do
    .notification.notification-danger.animated.fadeInRight
      = icon('exclamation')
      .notification-message
        =t 'spina.notifications.alert'
        %small= @project.errors.full_messages.join('<br />').html_safe
      = link_to '#', data: {close_notification: true} do
        = icon('cross')

%header#header
  .breadcrumbs
    = render_breadcrumbs separator: '<div class="divider"></div>'
    - unless @project.new_record?
      = link_to project_path(@project), target: :blank, class: 'button button-hollow button-small' do
        %i.icon.icon-export{style: 'margin: 0'}

  #header_actions
    %button.button.button-primary{ type: 'submit' }
      = icon('check')
      Save project
    = link_to t('spina.cancel'), spina.admin_projects_path, class: 'button button button-secondary'

#page_content.tab-content.active.well
  .horizontal-form
    .horizontal-form-group
      .horizontal-form-label
        SEO Title
      .horizontal-form-content
        = f.text_field :seo_title
    .horizontal-form-group
      .horizontal-form-label
        SEO Description
      .horizontal-form-content
        = f.text_field :seo_description
    .horizontal-form-group
      .horizontal-form-label
        Title
      .horizontal-form-content
        = f.text_field :title
    .horizontal-form-group
      .horizontal-form-label
        Category
      .horizontal-form-content
        %div{class: "select-dropdown #{@project.errors[:project_category_id].length > 0 ? 'error' : '' }"}
          = f.collection_select :project_category_id, Spina::ProjectCategory.all, :id, :name, { include_blank: 'Please Select' }
    .horizontal-form-group
      .horizontal-form-label
        Description
      .horizontal-form-content
        = render 'spina/admin/shared/rich_text_field', f: f, field: :description
    .horizontal-form-group
      .horizontal-form-label
        Location
      .horizontal-form-content
        = f.text_field :location
    .horizontal-form-group
      .horizontal-form-label
        Duration
      .horizontal-form-content
        = f.text_field :duration
    .horizontal-form-group
      .horizontal-form-label
        Completion date
      .horizontal-form-content
        = f.text_field :completion_date, value: (@project.completion_date.try(:strftime, "%d-%m-%Y") unless @project.new_record?), class: 'datepicker'
    .horizontal-form-group
      .horizontal-form-label
        Feature image
      .horizontal-form-content
        = link_to admin_media_picker_path(selected_ids: [f.object.image_id], hidden_field_id: 'media_picker_image_id'), remote: true, class: 'media_picker clearfix' do
          - if f.object&.image&.file&.attached?
            .placeholder.pull-right
              %span.button.button-small.button-round
                %i.icon.icon-dots
                = t('spina.images.choose_image')
            .image
              = image_tag variant(f.object.image.file, resize: "300x300^", crop: "300x300+0+0")
          - else
            .placeholder
              %span.button.button-small.button-round
                %i.icon.icon-dots
                = t 'spina.pages.image_picker'
          = f.hidden_field :image_id, data: { hidden_field_id: 'media_picker_image_id' }

    .horizontal-form-group
      .horizontal-form-label
        Images
      .horizontal-form-content
        = f.fields_for :image_collection, f.object.image_collection || f.object.build_image_collection do |ff|
          = link_to admin_media_picker_path(selected_ids: ff.object.image_ids, hidden_field_id: "media_picker_#{ff.object.object_id}", multiple: true), remote: true, class: 'media_picker clearfix' do
            .placeholder
              %span.button.button-small.button-round
                %i.icon.icon-dots
                = t('spina.images.choose_images')

            .image-collection
              - if ff.object.images.any?
                = render 'spina/admin/image_collections/image_collection', images: ff.object.images.sorted_by_image_collection

            = ff.hidden_field :image_tokens, value: ff.object.image_ids.join(","), data: { hidden_field_id: "media_picker_#{ff.object.object_id}" }
            = ff.hidden_field :image_positions, value: ff.object.images.sorted_by_image_collection.pluck(:image_id).join(","), class: 'image-positions'

    .horizontal-form-group
      .horizontal-form-label
        Testimonial
      .horizontal-form-content
        = f.text_area :testimonial
    .horizontal-form-group
      .horizontal-form-label
        Testimonial Author
      .horizontal-form-content
        = f.text_field :testimonial_name

    .horizontal-form-group
      .horizontal-form-label
        Publish date
      .horizontal-form-content
        = f.text_field :publish_date, value: (@project.publish_date.strftime("%d-%m-%Y") unless @project.new_record?), class: 'datepicker'

    .horizontal-form-group
      .horizontal-form-label
        Draft?
      .horizontal-form-content
        = f.check_box :draft, data: { switch: true }

- unless @project.new_record?
  .pull-right= link_to t('spina.permanently_delete'), spina.admin_project_path(@project.id), method: :delete, data: { confirm: t('spina.pages.delete_confirmation', subject: @project.title) }, class: 'button button-link button-danger'

app/views/spina/admin/projects/_project.html.haml
%li.dd-item{data: {id: project.id}}
  .dd-item-inner
    - if project.live?
      .project-status.live
    - if project.draft?
      .project-status.draft
    - if project.scheduled?
      .project-status.scheduled
    = link_to spina.edit_admin_project_path(project), class: 'button button-link button-small sortable-link' do
      = project.title
    %span.pull-right
      = link_to spina.edit_admin_project_path(project), class: 'button button-small button-link dd-nodrag' do
        = icon('pencil-outline')
        = t('spina.edit')

app/views/spina/admin/projects/categories.html.haml
%header#header
  .breadcrumbs
    = render_breadcrumbs seperator: '<div class="divider"></div>'

.permanent-notice.permanent-notice-info
  %p
    Blank categories will not be saved
    %small Please leave the input field blank if you don't need a category

= form_tag("/admin/projects/categories_update", remote: true, method: "PUT", class: "category-form") do
  .well
    .horizontal-form.category-form-group-parent
      - @categories.each do |category|
        .horizontal-form-group.category-form-group{ data: { parent: category.name.parameterize } }
          .horizontal-form-label
            = category.name
          .horizontal-form-content
            = text_field_tag category.name.parameterize, category.name, class: "category-form-field", disabled: true, data: { remove: false }
            %button.button.button-mini.button-link.pull-right.remove-category{ data: { name: category.name.parameterize } } Remove Category

      .horizontal-form-group.category-form-group.category-form-group-cloneable
        .horizontal-form-label
          .category-label
            Category name
        .horizontal-form-content
          = text_field_tag "project_category", "", placeholder: "Add a project category", class: "category-form-field category-form-field-new", data: { remove: false }

  .category-form-actions
    = submit_tag "Update categories", class: "button button-primary"
    %button.button.add-category
      = icon('plus')
      Add category

:javascript
  var ready = function() {
    let project_categories = [];

    $(".add-category").on("click", function() {
      event.preventDefault();

      const category_group = $(".category-form-group-cloneable:first").clone()
      category_group.find(".category-form-field").val("");
      category_group.find(".category-label").text("Category name");
      category_group.appendTo($(".category-form-group-parent"));
    });

    $(".remove-category").on("click", function() {
      event.preventDefault();

      const input = $("#" + $(this).attr("data-name"))
      input.attr("data-remove", true);
      $(this)
        .parent()
        .parent()
        .hide()
        .appendTo(".category-form");
    });

    $(".category-form-field").on("input", function() {
      const label = $(this)
        .parent()
        .parent()
        .find(".category-label");
      $(this).val() !== "" ? label.text($(this).val()) : label.text("Category name");
    })

    $(".category-form").on("submit", function() {
      $(".category-form-field").each(function(i, field) {
        if(field.value !== "") {
          project_categories.push({
            category_name: field.value,
            category_remove: field.getAttribute("data-remove")
          });
        }
      });

      $.ajax({
        type: "PUT",
        url: "/admin/projects/categories_update",
        data: { categories: project_categories },
        success: function() {
          window.location = "/admin/projects-categories"
        }
      });
    })
  }

  $(document).on("turbolinks:load", ready());


:scss
  .category-group {
    .button {
      margin: 4px 0 0 0;
    }
  }

  .category-form-actions {
    margin: 0 -20px;
  }

app/views/spina/admin/projects/edit.html.haml
= form_for [:admin, @project], url: spina.admin_project_path(@project.id), multipart: true, html: { autocomplete: "off" } do |f|
  = render 'form', f: f

app/views/spina/admin/projects/index.html.haml
- content_for(:permanent_notice) do
  - unless current_account.robots_allowed?
    .permanent-notice.permanent-notice-info
      = icon('search')
      %p
        =t 'spina.pages.invisible_to_search_engines'
        %small=t 'spina.pages.invisible_to_search_engines_description'

%header#header
  .breadcrumbs
    = render_breadcrumbs seperator: '<div class="divider"></div>'
    = link_to projects_path, target: :blank, class: 'button button-hollow button-small' do
      %i.icon.icon-export{style: 'margin: 0'}

  #header_actions
    = link_to '#pages_list', class: 'button sort-switch', data: {change_order: t('spina.pages.change_order'), done_changing_order: t('spina.pages.done_changing_order')} do
      = icon('random')
      = t('spina.pages.change_order')
    %span
      = link_to spina.new_admin_project_path, class: 'button button-primary' do
        = icon('plus')
        New project

.well
  - if @projects.any?
    .dd#pages_list{data: {"sort-url": spina.sort_admin_projects_url}}
      %ol.dd-list
        = render partial: 'project', collection: @projects
  - else
    %em No projects yet

:scss
  .project-status {
    height: 52px;
    left: 0;
    position: absolute;
    top: 0;
    transition: all 0.2s;
    width: 7px;

    &.live {
      background-color: #3adb76;
      z-index: 1;
    }

    &.draft {
      background-color: #767676;
    }

    &.scheduled {
      background-color: #1779ba;
    }
  }

app/views/spina/admin/projects/new.html.haml
= form_for [:admin, @project], multipart: true, html: { autocomplete: "off" } do |f|
  = render 'form', f: f